### ISSUE TITLE
The tutorial needs to be updated to reflect changes in the GitHub UI.

### ISSUE THREAD

**Issue by jzoldak** [edx/bok-choy#71]
From [this travis build](https://travis-ci.org/edx/bok-choy/builds/46321640). 

I'm guessing that something changed in the GitHub web app so that one of the css matchers is no longer matching.

```
====== Run tutorial examples
.
----------------------------------------------------------------------
Ran 1 test in 2.577s
OK
.E
======================================================================
ERROR: test_search (__main__.TestGitHub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "docs/code/round_2/test_search.py", line 27, in test_search
    self.github_search_page.visit().search_for_terms('user:edx repo:edx-platform')
  File "build/bdist.linux-x86_64/egg/bok_choy/page_object.py", line 64, in wrapper
    return method(self, *args, **kwargs)
  File "/home/travis/build/edx/bok-choy/docs/code/round_2/pages.py", line 51, in search_for_terms
    self.search()
  File "build/bdist.linux-x86_64/egg/bok_choy/page_object.py", line 64, in wrapper
    return method(self, *args, **kwargs)
  File "/home/travis/build/edx/bok-choy/docs/code/round_2/pages.py", line 43, in search
    GitHubSearchResultsPage(self.browser).wait_for_page()
  File "build/bdist.linux-x86_64/egg/bok_choy/page_object.py", line 326, in wait_for_page
    timeout=timeout
  File "build/bdist.linux-x86_64/egg/bok_choy/promise.py", line 96, in fulfill
    raise BrokenPromise(self)
BrokenPromise: Promise not satisfied: loaded page <pages.GitHubSearchResultsPage object at 0x7f40caee9690>
----------------------------------------------------------------------
Ran 2 tests in 37.259s
```

**Comment by jzoldak** [comment]
Closing this issue. Fixed in #73.
